#!/bin/bash

if [ $# -eq 0 ]; then
    echo "No file/link name provided"
    exit 1
fi

if [ "$1" = "-h" ]; then
	echo "Just use the command '0x0' followed by a file name or URL."
	exit 0
fi


# Post

if expr "$1" : '.*://.*\..*' > /dev/null; then
	echo 'Uploading url...'
	/bin/curl -F"url=$1" http://0x0.st/
else
	echo 'Uploading file...'
	/bin/curl -F"file=@$1" http://0x0.st/	
fi

